ville:
    path:     /ville
    defaults: { _controller: geoBundle:RegisterVille:register }

settr:
    path:     /settr
    defaults: { _controller: geoBundle:Page:settr }

game:
    path:     /game
    defaults: { _controller: geoBundle:Page:game }

gameReponse:
    path:     /game/reponse
    defaults: { _controller: geoBundle:Page:gameReponse }
